### ISSUE TITLE
Support for History and Playlists Bookmarks

### ISSUE THREAD

**Issue by StatelessOddity** [syhlx/plugin.video.piped#4]
Is there a possibility to implement Piped Watch History instead of using dedicated playlist? Maybe it's not possible, because some settings aren't stored on the instance server, but in browser memory, but I have no knowledge on how that works. Also, would it be possible to also sync bookmarked playlists with the addon?

Thank you for your work! :)

**Comment by syhlx** [comment]
To answer both of your questions:

### Use Piped built-in Watch History

Sadly, this is not possible.

As you mentionned, the Watch History feature built into Piped saves all its data in your browser and never sends it to the server.

This is why I implemented it using a playlist as a workaround.

This is a bit inconvenient, but you can still manually add a video to you Watch History playlist when you watch it outside of Kodi.

If the developers of Piped ever add a server-side Watch History in the future, I will definitely implement it to the Kodi addon.

### Sync Bookmarked Playlists

Same issue as with the Watch History: it is stored in the browser and never sent to the server.

However, if, instead of bookmarking it, you clone the playlist: it will show up in Kodi.\
The only issue with this being that if the original playlist changes, your cloned version will not.
