### ISSUE TITLE
Support for sent piped links with kore

### ISSUE THREAD

**Issue by fungs** [syhlx/plugin.video.piped#5]
With Kodi Youtube addon, it is possible to share a Youtube link from any (un)official Android client to Kodi using the 'share with' menu. Using a piped Android client like LibreTube one can also share links, eg like https://piped.video/watch?v=some_id, but this addon does not play the link since there seems to be no handler for it.

Would it be possible?

**Comment by jollySleeper** [comment]
+1 On this feature, tried many times to find how to create handlers for URLs in Plugin but never found the docs for it @syhlx if you guide me in right direction I'm willing to do it.

**Comment by syhlx** [comment]
As fasr as I know, there are two implementations of the "Play on Kodi" feature:

- Directly in Kore: https://github.com/xbmc/Kore/blob/master/app/src/main/java/org/xbmc/kore/utils/PluginUrlUtils.java#L91
- Using the SendToKodi Addon: https://github.com/firsttris/plugin.video.sendtokodi/blob/master/lib/yt_dlp/extractor/youtube.py#L326

The problem is that they both rely on hardcoded domain names.

In the case of Kore: With some modifications you could be able to send YouTube links to the Piped addon.

SendToKodi tends to list more domain names and could allow to send links from Piped plublic instances to the Piped addon.\
If you are running your own private instance of Piped, you would have to add your own instance to the SendToKodi addon's code.

**Comment by jollySleeper** [comment]
Will Check it out thanks

**Comment by fungs** [comment]
I was assuming, that Kore just sends a URL and handle would be implemented on Kodi side, but what you describe sounds very different. It would make more sense to me to uses a design like Android intent links and Kodi apps would register with those links.

If what you describe is accurate, which I believe, this sounds like a feature request for Kore to me. Would be great, if after evaluation and documentation here, we could propose this and link the issues. I'm willing to assist, if possible.

Thanks!
